In [1]:
import requests
import pandas as pd
import datetime

In [2]:
url = 'https://api.nextbike.net/maps/nextbike-live.json?city=362'
# timestamp = datetime.datetime.now()
# r = requests.get(url)
# data = r.json()
from requester import request_data
r = request_data(url)

In [3]:
data = r.json()
timestamp = datetime.datetime.now()

In [4]:
# example: get_city_specs(data, timestamp)
# here: timestamp = datetime.datetime.now()
# set it the moment data is fetchedfrom api just before.
def get_city_specs(data, time):

    country = data.get('countries')[0]
    city = country.get('cities')[0]
    city_dict = {
        'datetime'          : time,
        'city_id'           : city.get('uid'),
        'city_name'         : city.get('name'),
        'country'           : country.get('country'),
        'country_name'      : country.get('country_name'),
        'timezone'          : country.get('timezone'),
        'latitude'          : country.get('lat'),
        'longitute'         : country.get('lng'),
        'booked_bikes'      : country.get('booked_bikes'),
        'set_point_bikes'   : country.get('set_point_bikes'),
        'available_bikes'   : country.get('available_bikes'),
        'num_places'        : city.get('num_places'),
    }
    return pd.json_normalize(city_dict)

In [5]:
def get_bikes_stations(data, time):
    places = data.get('countries')[0].get('cities')[0].get('places')
    city = data.get('countries')[0].get('cities')[0]

    bikes = []
    stations = []

    for place in places:

        if place.get('bikes') > 0:
            for bike in place.get('bike_list'):
                bike_dic = {
                    'date'          : time,
                    'bike_id'       : bike.get('number'),
                    'bike_lat'      : place.get('lat'),
                    'bike_lng'      : place.get('lng'),
                    'bike_type'     : bike.get('bike_type'),
                    'active'        : bike.get('active'),
                    'state'         : bike.get('state'),
                    'electric_lock' : bike.get('electric_lock'),
                    'boardcomputer' : bike.get('boardcomputer'),
                    'is_standalone' : place.get('bike'),
                    'place_uid'     : place.get('uid'),
                    'place_number'  : place.get('number'),
                    'city_id'       : city.get('uid'),
                    'city_name'     : city.get('name')
                }
                bikes.append(bike_dic)

        if place.get('spot'):
            station_dic = {
                'date'                      : time,
                'place_uid'                 : place.get('uid'),
                'place_lat'                 : place.get('lat'),
                'place_lng'                 : place.get('lng'),
                'place_name'                : place.get('name'),
                'place_number'              : place.get('number'),
                'place_type'                : place.get('place_type'),
                'station_booked_bikes'      : place.get("booked_bikes"),
                'num_bikes'                 : place.get("bikes"),
                'bikes_available_to_rent'   : place.get('bikes_available_to_rent'),
                'bike_racks'                : place.get('bike_racks'),
                'free racks'                : place.get('free_racks'),
                'special_racks'             : place.get('special_racks'),
                'free_special_racks'        : place.get('free_special_racks'),
                'terminal_type'             : place.get('terminal_type'),
                'rack_locks'                : place.get('rack_locks'),
                'city_id'                   : city.get('uid'),
                'city_name'                 : city.get('name')
            }
            stations.append(station_dic)

    return pd.json_normalize(bikes), pd.json_normalize(stations)

In [6]:
bikes, stations = get_bikes_stations(data, timestamp)

In [7]:
city_info = get_city_specs(data, timestamp)

In [8]:
city_info

,datetime,city_id,city_name,country,country_name,timezone,latitude,longitute,booked_bikes,set_point_bikes,available_bikes,num_places
0,2025-04-21 18:43:01.498949,362,Berlin,DE,Germany,Europe/Berlin,52.5174,13.4055,32,6174,4428,5987

In [9]:
bikes

,date,bike_id,bike_lat,bike_lng,bike_type,active,state,electric_lock,boardcomputer,is_standalone,place_uid,place_number,city_id,city_name
0,2025-04-21 18:43:01.498949,18157,52.496986,13.291210,196,True,ok,True,7551136396,False,72228,1670,362,Berlin
1,2025-04-21 18:43:01.498949,17747,52.496986,13.291210,196,True,ok,True,7551129206,False,72228,1670,362,Berlin
2,2025-04-21 18:43:01.498949,15101,52.496986,13.291210,196,True,ok,True,7551122749,False,72228,1670,362,Berlin
3,2025-04-21 18:43:01.498949,19046,52.498323,13.296157,196,True,ok,True,7551120218,False,72229,1669,362,Berlin
4,2025-04-21 18:43:01.498949,17929,52.499137,13.303743,196,True,ok,True,7551136989,False,72238,1672,362,Berlin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4423,2025-04-21 18:43:01.498949,17417,52.549844,13.393437,196,True,ok,True,7551128846,True,529049827,0,362,Berlin
4424,2025-04-21 18:43:01.498949,15442,52.532831,13.385679,150,True,ok,True,7551141241,True,529049840,0,362,Berlin
4425,2025-04-21 18:43:01.498949,14423,52.484187,13.406632,150,True,ok,True,83300005647,True,529049849,0,362,Berlin
4426,2025-04-21 18:43:01.498949,19291,52.558596,13.156338,150,True,ok,True,7551142599,True,529049855,0,362,Berlin
4427,2025-04-21 18:43:01.498949,17465,52.501458,13.396826,196,True,ok,True,7551109576,True,529049876,0,362,Berlin

In [10]:
stations

,date,place_uid,place_lat,place_lng,place_name,place_number,place_type,station_booked_bikes,num_bikes,bikes_available_to_rent,bike_racks,free racks,special_racks,free_special_racks,terminal_type,rack_locks,city_id,city_name
0,2025-04-21 18:43:01.498949,44437,52.504157,13.335328,virtuell - Kurfürstendamm/Rankestraße,1640,17,0,0,0,4,4,0,0,free,False,362,Berlin
1,2025-04-21 18:43:01.498949,72228,52.496986,13.291210,virtuell - EDEKA Schmitt (S Halensee),1670,17,0,3,3,4,1,0,0,free,False,362,Berlin
2,2025-04-21 18:43:01.498949,72229,52.498323,13.296157,Joachim-Friedrich-Str./KuDamm | BONUS-Station:...,1669,27,0,1,1,5,4,0,0,smart_sign,False,362,Berlin
3,2025-04-21 18:43:01.498949,72238,52.499137,13.303743,Albrecht-Achilles-Straße | BONUS-Station: Retu...,1672,27,0,2,2,5,3,0,0,smart_sign,False,362,Berlin
4,2025-04-21 18:43:01.498949,72263,52.500614,13.294401,Karlsruher Str./Aspria | BONUS-Station: Return...,1671,27,0,4,4,8,4,0,0,smart_sign,False,362,Berlin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4440,2025-04-21 18:43:01.498949,518696076,52.485009,13.387072,Jelbi U Platz der Luftbrücke (TEM/PLA),13926,18,0,0,0,4,4,0,0,traffic_sign,False,362,Berlin
4441,2025-04-21 18:43:01.498949,518700574,52.463508,13.394723,Jelbi Felixstraße/Götzstraße (TEM/FEL),13927,18,0,0,0,4,4,0,0,traffic_sign,False,362,Berlin
4442,2025-04-21 18:43:01.498949,518701718,52.464290,13.411340,Jelbi Oberlandstraße/Atelier Gardens (TEM/OB),13928,18,0,0,0,5,5,0,0,,False,362,Berlin
4443,2025-04-21 18:43:01.498949,521313230,52.504427,13.442107,virtuell - Uber Platz (Mühlenstraße),13929,17,0,1,1,4,2,0,0,free,False,362,Berlin
4444,2025-04-21 18:43:01.498949,523749684,52.466991,13.328465,Jelbi U Walther-Scheiber-Platz/Lefèvrestraße (...,13931,18,0,1,1,1,0,0,0,traffic_sign,False,362,Berlin

In [51]:
now = datetime.datetime.now()

In [68]:
now.strftime("%Y-%m-%d")

'2025-04-17'